version: 0.2

env:
  variables:
    REGION: "us-east-2"
    REPOSITORY_URI: "836156348866.dkr.ecr.us-east-2.amazonaws.com/react-portoflio"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin 836156348866.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t react-portoflio .
      - docker tag react-portoflio:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
